### ISSUE TITLE
更新到2020.0之后打不开

### ISSUE THREAD

**Issue by lygoing** [lework/RedisDesktopManager-Windows#10]
![image](https://user-images.githubusercontent.com/5944432/80554890-28a93680-8a01-11ea-9108-e704fb367cdb.png)
提示有新版本，但是点击确定后窗口消失，之后没有任何反应了

**Comment by lzysuqianqiu** [comment]
same question

**Comment by 664623107** [comment]
same question

**Comment by lework** [comment]
此次更新涉及到了几个问题

1. qmake时需指定版本
2. qt版本升级到5.13

现已修复，请重新下载安装：https://github.com/lework/RedisDesktopManager-Windows/releases/download/2020.0/redis-desktop-manager-2020.0.zip

**Comment by lygoing** [comment]
@lework  哇，谢谢 ☕
