### ISSUE TITLE
键数量更新 问题

### ISSUE THREAD

**Issue by AutismSuperman** [lework/RedisDesktopManager-Windows#14]
不知道为什么  在win10 中键的数量总是不能更新  QAQ
![image](https://user-images.githubusercontent.com/34642987/81521114-dd841180-9378-11ea-9b57-6ee0410162e8.png)

**Comment by lework** [comment]
使用第4个图标可以打开实时更新

**Comment by AutismSuperman** [comment]
> 使用第4个图标可以打开实时更新

![image.png](https://i.loli.net/2020/05/14/B6Jw9UCPFdT7qVc.png)
db0 上那个数好像没奏效

**Comment by lework** [comment]
软件功能问题，可以反馈给作者 https://github.com/uglide/RedisDesktopManager/issues
