### ISSUE TITLE
Official  RedisDesktopManager is now available on Microsoft Store

### ISSUE THREAD

**Issue by uglide** [lework/RedisDesktopManager-Windows#15]
Hello @lework 

Thanks a lot for adding a note in README.

Starting from today RedisDesktopManager is available on Microsoft Store with super fair price **¥49.00** for users from China https://www.microsoft.com/store/apps/9NDK76ZVZ3TM?cid=storebadge&ocid=badge

No more f***ing sign-in, subscriptions, recurring payments, slow downloads - only fair price for support open-source project with bonus auto-updates. 

Please update note and if possible add Get it from Microsoft button in your README.

Thanks for your time.

```
<a target="_blank" href='//www.microsoft.com/store/apps/9NDK76ZVZ3TM?cid=storebadge&ocid=badge'>
<img height="50" src='https://developer.microsoft.com/en-us/store/badges/images/Chinese_Simplified_Get_L.png' alt='Get it from Microsoft'/>
</a>
```

**Comment by lework** [comment]
@uglide Thank you for your contribution, I have added an introduction guide in README.

**Comment by uglide** [comment]
@lework thanks a lot!
