### ISSUE TITLE
2020.3 安装后打开没反应，2020.2没问题

### ISSUE THREAD

**Issue by pikadun** [lework/RedisDesktopManager-Windows#18]

**Comment by hutaoseven** [comment]
我也是，各种尝试，都不行

**Comment by Dante-X** [comment]
确实,点击后任务管理器有进程界面没打开

**Comment by jfcherng** [comment]
@lework 推薦嘗試更新 Qt 5.14, 我這邊 build 沒問題

**Comment by shuohao** [comment]
我的也是 没反应

**Comment by lework** [comment]
@jfcherng 谢谢提醒，我更新后，重新编译就可以了。
@shuohao @hutaoseven @Dante-X @pikadun 各位请重新下载安装包  https://github.com/lework/RedisDesktopManager-Windows/releases/download/2020.3/redis-desktop-manager-2020.3.zip

**Comment by shuohao** [comment]
> @jfcherng 谢谢提醒，我更新后，重新编译就可以了。
> @shuohao @hutaoseven @Dante-X @pikadun 各位请重新下载安装包 https://github.com/lework/RedisDesktopManager-Windows/releases/download/2020.3/redis-desktop-manager-2020.3.zip

![image](https://user-images.githubusercontent.com/4637107/92901740-4c6e9580-f453-11ea-87c0-b7ed4a2e89b4.png)
