### ISSUE TITLE
请问支持编译32位安装包吗

### ISSUE THREAD

**Issue by iamsxm** [lework/RedisDesktopManager-Windows#21]
目前使用的deepin操作系统，不支持snap，用wine可以运行2020.2版本的32位安装包，但是太老了

**Comment by WebPavel** [comment]
you can download deb from [redis-desktop-manager_0.9.0.17_amd64.deb](http://packages.deepin.com/deepin/pool/non-free/r/redis-desktop-manager/redis-desktop-manager_0.9.0.17_amd64.deb). But it hasn't deb which is x86 arch

**Comment by WebPavel** [comment]
> > 目前使用的deepin操作系统，不支持snap，用wine可以运行2020.2版本的32位安装包，但是太老了
> 
> 它有Linux版本的啊，而且Linux版本的好像免费的啊，干嘛用win的啊

please note question which metions that deepin doesn't support snap.
[RDM](https://rdm.dev/) also only offer snap
