### ISSUE TITLE
哥们下载的安装包有病毒，太不讲究了。

### ISSUE THREAD

**Issue by westek** [lework/RedisDesktopManager-Windows#22]
哥们下载的安装包有病毒，太不讲究了。

**Comment by anjia0532** [comment]
https://www.virustotal.com/gui/url/53aafd4dad9454b78370696db9ca1bd3d5ea4becfb6a65996a64160b546392ce/detection

**Comment by AncientFairy** [comment]
对，我也没发现病毒啊，不会你找的国内下载网站的吗？

**Comment by lework** [comment]
额，我这个拉取作者源代码编译的，里面啥都没改。

**Comment by fat8701** [comment]
黑子
