### ISSUE TITLE
Formatters: Cannot import module: formatters (bad magic number in 'formatters': b'a\r\r\n') 

### ISSUE THREAD

**Issue by esverde** [lework/RedisDesktopManager-Windows#26]
启动日志显示这个
Formatters: Cannot import module: formatters (bad magic number in 'formatters': b'a\r\r\n')
Formatters: Function not found: 'formatters.get_formatters_list' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'formatters' is not defined
)

**Comment by lework** [comment]
最近两个版本修复了这个问题。
