### ISSUE TITLE
能否编译下2021.9.4的

### ISSUE THREAD

**Issue by WEGFan** [lework/RedisDesktopManager-Windows#27]
2021.9有个崩溃的bug，作者后来修复了，麻烦编译一下最新版本，谢谢

https://github.com/uglide/RedisDesktopManager/releases/tag/2021.9.4

**Comment by lework** [comment]
已经编译好了：https://github.com/lework/RedisDesktopManager-Windows/releases/tag/2021.9.4

**Comment by zkteco-home** [comment]
Hi,if you need to use Redis7.0 for windows,you can visit zkteco-home/redis-windows,it is native port of redis for windows
