### ISSUE TITLE
windows安全中心报毒

### ISSUE THREAD

**Issue by tanglei5** [lework/RedisDesktopManager-Windows#31]
老哥 下载完成windows11 直接干掉了。

<a href="https://www.helloimg.com/image/GrxWND"><img src="https://www.helloimg.com/images/2022/02/22/GrxWND.png" alt="GrxWND.png" border="0" /></a>

点击 了解更多后显示的

<a href="https://www.helloimg.com/image/Grx9uS"><img src="https://www.helloimg.com/images/2022/02/22/Grx9uS.png" alt="Grx9uS.png" border="0" /></a>

**Comment by lework** [comment]
我这里并没有爆出这个问题。。
