### ISSUE TITLE
由于找不到python37.dll

### ISSUE THREAD

**Issue by chenjia123** [lework/RedisDesktopManager-Windows#4]
![image](https://user-images.githubusercontent.com/22190625/65009851-afad1100-d940-11e9-9f18-88a82477dbf4.png)

**Comment by lework** [comment]
需要安装python3

**Comment by findix** [comment]
安装好 Python 后，从 Python 根路径下复制 python37.dll 至 RedisDesktopManager 安装路径即可
[python37.zip](https://github.com/lework/RedisDesktopManager-Windows/files/3720322/python37.zip)

**Comment by jfcherng** [comment]
只放置 `python37.dll` 應該是不夠的，官方版裡放了三個檔案，推測放了應該無須安裝 python （因為我電腦上裝的是 python 3.8 ）。

[python37-deps.zip](https://github.com/lework/RedisDesktopManager-Windows/files/3739039/python37-deps.zip)

![image](https://user-images.githubusercontent.com/6594915/67006457-c4cfb800-f117-11e9-81ca-708e9428fd20.png)

**Comment by lework** [comment]
@jfcherng 非常感谢您的依赖提供。已经将您的代码合并，并且更新了2019.4版本上。
