### ISSUE TITLE
请问一下为什么会报毒

### ISSUE THREAD

**Issue by AirBashX** [lework/RedisDesktopManager-Windows#7]
我在安装过程中360提示我有病毒,是误报吗?

**Comment by lework** [comment]
不清楚，我在安装的时候没有报毒，我的是腾讯管家

**Comment by pixiandouban** [comment]
> 
> 
> 我在安装过程中360提示我有病毒,是误报吗?

这个是 Virustotal 的扫描结果。

**Comment by lework** [comment]
我来帖下检测结果[Virustotal ](https://www.virustotal.com/gui/url/2edbc86b6729e0cd50b4d5bc6536f83c88e7605718ea5e4b01a7d97869b88fd3/detection)， 有可能360误报。
